### ISSUE TITLE
link to open a specific tab on page

### ISSUE THREAD

**Issue by tellithy** [Weebly/tabs-app#11]
I'm trying to figure out a way to open a specific tab on a page from a button on a different page and im using the tabs app in weebly. I tried using java script to accomplish this with no success. script below. please help

 <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.0.3.min.js"></script>

    <script>

    $(document).ready(function () {
        var tab = getUrlParameter("tab");
        if ((tab) && (tab != "0")) {
            $("ul.tabbed-box-tab-group").find("li.tabbed-box-tab").each(function (idx) {
                if (idx == 0) {
                    $(this).removeClass("active");
			$(this).unbind('click');
                } else if (idx == tab) {
                    $(this).addClass("active");
                }
            });

        }
    });

    function getUrlParameter(name) {
        name = name.replace(/[\[]/, '\\[').replace(/[\]]/, '\\]');
        var regex = new RegExp('[\\?&]' + name + '=([^&#]*)');
        var results = regex.exec(location.search);
        return results === null ? '' : decodeURIComponent(results[1].replace(/\+/g, ' '));
    };

    </script>

**Comment by szainmehdi** [comment]
Hi @tellithy,

Unfortunately, I don't think there's an easy way to pre-select a tab using external javascript. To do this, you'd need to listen to a non-existent post-element-render event.
